name: Run CMake checks

on:
  push:
    branches: [PHP-8.3]
    paths-ignore:
      - 'docs/**'
      - '.editorconfig'
      - '.gitignore'
      - 'README.md'
  pull_request:
    branches: [PHP-8.3]
    paths-ignore:
      - 'docs/**'
      - '.editorconfig'
      - '.gitignore'
      - 'README.md'

jobs:
  check:
    name: Check CMake files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Setup PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install checking tools
        run: |
          pipx install cmakelint
          pipx install cmakelang
          pipx install codespell
          curl -OL https://github.com/petk/normalizator/releases/latest/download/normalizator.phar
          chmod +x normalizator.phar
          mv normalizator.phar /usr/local/bin/normalizator

      - name: Run CMake checks
        run: ./bin/check-cmake.sh
